FROM node:9.10.1

LABEL author="Juan Pedro Perez"
LABEL email="jp.perez.alcantara@gmail.com"

# Install packages
RUN ["npm", "install", "-g", "gulp"]
RUN ["npm", "install", "-g", "typescript"]

# Run
ENTRYPOINT ["/bin/bash"]
